environments:
  production:

repositories:
- name: bitnami
  url: https://charts.bitnami.com/bitnami

releases:
- name: external-dns
  chart: bitnami/external-dns
  version: 3.2.3
  values:
  - ./config/external-dns-values.yaml.gotmpl
